
-- Q1. What is the total revenue generated by male vs. female customers?

SELECT 
    ROW_NUMBER() OVER (ORDER BY SUM(Purchase_Amount_) ASC) AS ``,
    gender,
    FORMAT(SUM(Purchase_Amount_), 0) AS revenue
FROM customer
GROUP BY gender
ORDER BY SUM(Purchase_Amount_) ASC;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT 
    ROW_NUMBER() OVER () AS ``,
    customer_id,
    purchase_amount_
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_ >= (
    SELECT AVG(purchase_amount_) 
    FROM customer
);
-- Q3. Which are the top 5 products with the highest average review rating?

SELECT 
    ROW_NUMBER() OVER (ORDER BY AVG(review_rating) DESC) AS ``,
    item_purchased, 
    ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4.  compare average purchase amounts for shipping types

SELECT 
    ROW_NUMBER() OVER () AS ``,
    shipping_type,
    ROUND(AVG(purchase_amount_), 2) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT 
row_number() over() as ``,
    Subscription_Status, 
      COUNT(*) AS "Total Customers",
    ROUND(AVG(Purchase_amount_), 2) AS "Average Spend", 
    SUM(Purchase_amount_) AS "Total Revenue"
FROM customer
GROUP BY Subscription_Status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    ROW_NUMBER() OVER (ORDER BY (COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)) DESC) AS ``,
    item_purchased, 
    ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*), 2) AS "Discount Percentage"
FROM customer
GROUP BY item_purchased
ORDER BY "Discount Percentage" DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
SELECT
row_number()over() AS ``,
 customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select 
row_number()over() AS ``,
customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

SELECT 
    ROW_NUMBER() OVER () AS ``,
    ranking AS "Category Rank",
    Category, 
    Item_Purchased, 
    purchase_count AS "Total Sales"
FROM (
    SELECT 
        Category, 
        Item_Purchased, 
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS ranking
    FROM customer
    GROUP BY Category, Item_Purchased
) AS ranked_products
WHERE ranking <= 3
ORDER BY Category, ranking;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
row_number() over() as ``,
    Subscription_Status, 
    COUNT(*) AS "Number of Repeat Buyers",
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer WHERE Previous_Purchases > 5), 2) AS "Percentage"
FROM customer
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status;

-- Q10. What is the revenue contribution of each age group? 

SELECT 
    ROW_NUMBER() OVER (ORDER BY SUM(purchase_amount_) DESC) AS ``,
    age_group, 
    FORMAT(SUM(purchase_amount_), 0) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY SUM(purchase_amount_) DESC;

